package javascript

import "errors"

// Errors
var (
	ErrInvalidQuoted                        = errors.New("invalid quoted string")
	ErrInvalidMethodName                    = errors.New("invalid method name")
	ErrInvalidPropertyName                  = errors.New("invalid property name")
	ErrInvalidClassDeclaration              = errors.New("invalid class declaration")
	ErrInvalidCallExpression                = errors.New("invalid CallExpression")
	ErrMissingOptional                      = errors.New("missing optional chain punctuator")
	ErrInvalidOptionalChain                 = errors.New("invalid OptionalChain")
	ErrInvalidFunction                      = errors.New("invalid function")
	ErrReservedIdentifier                   = errors.New("reserved identifier")
	ErrNoIdentifier                         = errors.New("missing identifier")
	ErrMissingFunction                      = errors.New("missing function")
	ErrMissingOpeningParenthesis            = errors.New("missing opening parenthesis")
	ErrMissingClosingParenthesis            = errors.New("missing closing parenthesis")
	ErrMissingOpeningBrace                  = errors.New("missing opening brace")
	ErrMissingClosingBrace                  = errors.New("missing closing brace")
	ErrMissingOpeningBracket                = errors.New("missing opening bracket")
	ErrMissingClosingBracket                = errors.New("missing closing bracket")
	ErrMissingComma                         = errors.New("missing comma")
	ErrMissingArrow                         = errors.New("missing arrow")
	ErrMissingCaseClause                    = errors.New("missing case clause")
	ErrMissingExpression                    = errors.New("missing expression")
	ErrMissingCatchFinally                  = errors.New("missing catch/finally block")
	ErrMissingSemiColon                     = errors.New("missing semi-colon")
	ErrMissingColon                         = errors.New("missing colon")
	ErrMissingInitializer                   = errors.New("missing initializer")
	ErrInvalidStatementList                 = errors.New("invalid statement list")
	ErrInvalidStatement                     = errors.New("invalid statement")
	ErrInvalidDeclaration                   = errors.New("invalid declaration")
	ErrInvalidLexicalDeclaration            = errors.New("invalid lexical declaration")
	ErrInvalidAssignment                    = errors.New("invalid assignment operator")
	ErrInvalidSuperProperty                 = errors.New("invalid super property")
	ErrInvalidMetaProperty                  = errors.New("invalid meta property")
	ErrInvalidTemplate                      = errors.New("invalid template")
	ErrInvalidAsyncArrowFunction            = errors.New("invalid async arrow function")
	ErrInvalidImport                        = errors.New("invalid import statement")
	ErrInvalidExportDeclaration             = errors.New("invalid export declaration")
	ErrInvalidNameSpaceImport               = errors.New("invalid namespace import")
	ErrMissingFrom                          = errors.New("missing from")
	ErrMissingModuleSpecifier               = errors.New("missing module specifier")
	ErrInvalidNamedImport                   = errors.New("invalid named import list")
	ErrInvalidImportSpecifier               = errors.New("invalid import specifier")
	ErrInvalidExportClause                  = errors.New("invalid export clause")
	ErrDuplicateDefaultClause               = errors.New("duplicate default clause")
	ErrInvalidIterationStatementDo          = errors.New("invalid do iteration statement")
	ErrInvalidIterationStatementWhile       = errors.New("invalid while iteration statement")
	ErrInvalidIterationStatementFor         = errors.New("invalid for iteration statement")
	ErrInvalidForLoop                       = errors.New("invalid for loop")
	ErrInvalidForAwaitLoop                  = errors.New("invalid for await loop")
	ErrInvalidIfStatement                   = errors.New("invalid if statement")
	ErrInvalidSwitchStatement               = errors.New("invalid switch statement")
	ErrInvalidWithStatement                 = errors.New("invalid with statement")
	ErrInvalidTryStatement                  = errors.New("invalid try statement")
	ErrInvalidVariableStatement             = errors.New("invalid variable statement")
	ErrLabelledFunction                     = errors.New("LabelledItemFunction not allowed here")
	ErrInvalidCharacter                     = errors.New("invalid character")
	ErrInvalidSequence                      = errors.New("invalid character sequence")
	ErrInvalidRegexpCharacter               = errors.New("invalid regexp character")
	ErrInvalidRegexpSequence                = errors.New("invalid regexp sequence")
	ErrInvalidNumber                        = errors.New("invalid number")
	ErrUnexpectedBackslash                  = errors.New("unexpected backslash")
	ErrInvalidUnicode                       = errors.New("invalid unicode escape sequence")
	ErrInvalidEscapeSequence                = errors.New("invalid escape sequence")
	ErrUnexpectedLineTerminator             = errors.New("line terminator in string")
	ErrBadRestElement                       = errors.New("bad rest element")
	ErrInvalidAssignmentProperty            = errors.New("invalid assignment property")
	ErrInvalidDestructuringAssignmentTarget = errors.New("invalid DestructuringAssignmentTarget")
	ErrNotSimple                            = errors.New("not a simple expression")
	ErrMissingString                        = errors.New("missing string value")
	ErrMissingAttributeKey                  = errors.New("missing attribute key")
)
